/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clearcut_HelloWorld */

#ifndef _Included_clearcut_HelloWorld
#define _Included_clearcut_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clearcut_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clearcut_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
