/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clearcut_Clearcut */

#ifndef _Included_clearcut_Clearcut
#define _Included_clearcut_Clearcut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clearcut_Clearcut
 * Method:    clearcutMain
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_clearcut_Clearcut_clearcutMain
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
